// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk4TIEBEjP0JJgRlsKosxueIKHBDtL1AE',
    appId: '1:917322099017:web:790febfe11d0b725d11298',
    messagingSenderId: '917322099017',
    projectId: 'quick-cart-dca0e',
    authDomain: 'quick-cart-dca0e.firebaseapp.com',
    storageBucket: 'quick-cart-dca0e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7dn04RrfJVvcK4vGZgWCSF7scQKr4InY',
    appId: '1:917322099017:android:e4bef35d3dce7be6d11298',
    messagingSenderId: '917322099017',
    projectId: 'quick-cart-dca0e',
    storageBucket: 'quick-cart-dca0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe5QNIbH0U-OetWbzs2NUBvluMntBisK0',
    appId: '1:917322099017:ios:3f9f3a1af10e902bd11298',
    messagingSenderId: '917322099017',
    projectId: 'quick-cart-dca0e',
    storageBucket: 'quick-cart-dca0e.firebasestorage.app',
    androidClientId: '917322099017-3jk29q72vkcu519iunu3r8n1s2gd8okl.apps.googleusercontent.com',
    iosClientId: '917322099017-sjq4usrda01e5f1gn12ttjpvsd3uja8i.apps.googleusercontent.com',
    iosBundleId: 'com.example.quicksCart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe5QNIbH0U-OetWbzs2NUBvluMntBisK0',
    appId: '1:917322099017:ios:3f9f3a1af10e902bd11298',
    messagingSenderId: '917322099017',
    projectId: 'quick-cart-dca0e',
    storageBucket: 'quick-cart-dca0e.firebasestorage.app',
    androidClientId: '917322099017-3jk29q72vkcu519iunu3r8n1s2gd8okl.apps.googleusercontent.com',
    iosClientId: '917322099017-sjq4usrda01e5f1gn12ttjpvsd3uja8i.apps.googleusercontent.com',
    iosBundleId: 'com.example.quicksCart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk4TIEBEjP0JJgRlsKosxueIKHBDtL1AE',
    appId: '1:917322099017:web:3f176049d246f6ecd11298',
    messagingSenderId: '917322099017',
    projectId: 'quick-cart-dca0e',
    authDomain: 'quick-cart-dca0e.firebaseapp.com',
    storageBucket: 'quick-cart-dca0e.firebasestorage.app',
  );
}
